### ISSUE TITLE
win64 py3.7 error

### ISSUE THREAD

**Issue by creboy** [wblgers/music_retrieve#1]
Traceback (most recent call last):
  File "F:\dm\music_retrieve-master(f)\librosa_music.py", line 16, in <module>
    beat_frames = librosa.feature.delta(beat_frames)
  File "C:\py3\lib\site-packages\librosa\feature\utils.py", line 102, in delta
    "cannot exceed data.shape[axis]={}".format(width, data.shape[axis]))
librosa.util.exceptions.ParameterError: when mode='interp', width=9 cannot exceed data.shape[axis]=2

**Comment by wblgers** [comment]
Please comment on your python version and librosa version
